[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true # recursive auto-detection of remappings
evm_version = 'paris'
gas_reports = ['*']
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
